services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: job_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net1
    ports:
      - "5432:5432"
    restart: always

  django_app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - net1
    restart: always


  react_app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django_app


  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile

    networks:
      - net1



volumes:
  pgdata:
  frontend:


networks:
  net1: